format = """
$username \
$directory \
$git_branch\
$git_status\
$fill\
$time \
\n$character"""

[fill]
symbol = ' '

[username]
show_always = true
format = '[$user](bold fg:#373e50)'

[directory]
format = "[$path](bold fg:#445f96)"
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
symbol = ""
format = '[$symbol$branch](bold fg:#825c45)'

[git_status]
format = '|[$all_status$ahead_behind](bold fg:#c87b2e)'

[time]
disabled = false
time_format = "%d.%m.%Y %R" # Hour:Minute Format
format = '[$time](bold fg:#1b1b1b)'
