os:
  editPreset: nvim
git:
  diffRenderers:
    - colorArg: always
      command: delta --light --paging=never --line-numbers
    - colorArg: always
      command: delta --light --paging=never --line-numbers --side-by-side
    - colorArg: always
      type: rawGit
